<?php
/** \N23\Videoplayer\Block\Videoplayer $block */
$videoplayer = $block->getVideoplayer()
?>
<div id="container">
    <video
	    controls
	    crossorigin
	    playsinline
	    data-poster="<?= $block->getBaseUrl().'pub/media/'.$videoplayer->getImage(); ?>"
	    id="player<?= $videoplayer->getId(); ?>"
    >
    <!-- Video files -->
    <source
	    src="<?= $block->getBaseUrl().'pub/media/'.$videoplayer->getVideo(); ?>"
	    type="video/mp4"
	    size="576"
    />
    <source
        src="<?= $block->getBaseUrl().'pub/media/'.$videoplayer->getVideo(); ?>"
        type="video/mp4"
        size="720"
    />
    <source
        src="<?= $block->getBaseUrl().'pub/media/'.$videoplayer->getVideo(); ?>"
        type="video/mp4"
        size="1080"
    />

    <!-- Caption files -->
    <track
        kind="captions"
        label="English"
        srclang="en"
        src="https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-HD.en.vtt"
        default
    />
    <track
        kind="captions"
        label="Français"
        srclang="fr"
        src="https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-HD.fr.vtt"
    />

    <!-- Fallback for browsers that don't support the <video> element -->
    <a href="https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-576p.mp4" download>Download</a>
  </video>
</div>
<h3><?= $block->escapeHtml($videoplayer->getVideo()) ?></h3>

<script type="text/javascript">
    require(['jquery','plyr'],function($){
        $(window).load(function() {
            const player = new Plyr('#player1', {
			    fullscreen:{ enabled: true, fallback: true, iosNative: true },
			    controls:['play-large', 'play', 'progress', 'current-time', 'mute', 'volume', 'captions', 'settings', 'pip', 'airplay', 'fullscreen', 'download']
			});
        });
    });
</script>
